In [ ]:
%%sql
    
SELECT 
    column_a, 
    column_b, 
    column_c
FROM 
    table
ORDER BY 
    1,2,3;

In [ ]:
%%sql

-- Esta consulta detecta se há duplicatas na tabela. Caso retorne 0, não há duplicatas.

SELECT COUNT(*), 
FROM (
    SELECT 
        column_a, 
        column_b, 
        column_c
    COUNT(*) as records
    FROM 
        table
    GROUP BY 
        1,2,3
    ) AS t
WHERE 
    records > 1;

In [ ]:
%%sql

-- como alternativa a uma subconsulta podemos usar o HAVING

SELECT 
    column_a, 
    column_b, 
    column_c, 
    COUNT(*) as records
FROM 
    table
GROUP BY 
    1,2,3
HAVING 
    COUNT(*) > 1;

In [ ]:
%%sql 

-- podemos ainda listar todos os registros duplicados

SELECT * 
FROM 
    (SELECT 
        column_a, 
        column_b, 
        column_c, 
        COUNT(*) as records
    FROM 
        table
    GROUP BY 
        1,2,3
    ) AS t
WHERE records = 2;

In [ ]:
%%sql

-- total de pedidos por cliente

SELECT orders, count(*) as num_customers
FROM
(
 SELECT customer_id, count(order_id) as orders
 FROM orders
 GROUP BY 1
) a
GROUP BY 1
;

In [ ]:
%%sql

SELECT  
  id_obra, 
  count(*) as number_count
FROM 
  (
    SELECT 
    id_obra,  
    count(*) as count_2
    FROM  `rj-smi.infraestrutura_siscob_obras.localizacao` 
    GROUP BY 1
  )  AS t
  GROUP BY 1
  ORDER BY 1 DESC;

In [ ]:
%%sql

SELECT id_obra, id_bairro, bairro, id_regiao_planejamento, COUNT(*) AS registros
    FROM  `rj-smi.infraestrutura_siscob_obras.localizacao` 
GROUP BY 1, 2, 3, 4
HAVING COUNT(*) > 1
ORDER BY registros DESC;